builds:
- main: couchbase_exporter.go
  binary: couchbase_exporter
- env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  goarch:
    - 386
    - amd64
    - arm
    - arm64

archive:
  format: tar.gz
  name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  files:
    - LICENSE.txt
    - metrics/*