groups:
- name: Couchbase
  rules:
  
  - alert: Couchbase_Failover
    expr: cb_cluster_failover_node_count{job="Couchbase"} - avg_over_time(cb_cluster_failover_node_count{job="Couchbase"}[1m]) > 0
    annotations:
      summary: Couchbase cluster failover
      description: Couchbase cluster suffers from a failover. Please check cluster state.
  
  - alert: Couchbase_Bucket_Commit_Failed
    expr: cb_bucket_ep_item_commit_failed > 0
    annotations:
      summary: Couchbase bucket commit failed
      description: A failure occured when committing data to disk for bucket {{ $labels.bucket }}.
  
  - alert: Couchbase_Rebalance_Failed
    expr: cb_cluster_rebalance_fail_count{job="Couchbase"} - avg_over_time(cb_cluster_rebalance_fail_count{job="Couchbase"}[1m]) > 0
    annotations:
      summary: Couchbase cluster failover
      description: Couchbase cluster suffers from a failover. Please check cluster state.
  
  - alert: Couchbase_Node_Cluster_Membership
    expr: cb_node_cluster_membership == 0
    annotations:
      summary: Couchbase node cluster membership
      description: Node {{ $labels.instance }} is out of the cluster.